version: "3"

services:
  src:
    build:
      context: .
    ports: 
      - "8000:8000"
    volumes:
      - ./src:/src # maps src directory to docker src directory
    command: >      # > for going to the next line
      sh -c "python manage.py runserver 0.0.0.0:8000"    # shell for sh -c to run the cmd in shell
    